[package]
name = "codex-switcher"
version = "0.2.20"
description = "A command-line account manager for Codex"
authors = ["lampese"]
edition = "2021"
rust-version = "1.89"

[dependencies]
anyhow = "1"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
dirs = "6"
rand = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tempfile = "3"
tiny_http = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "signal"] }
toml_edit = "0.25.15"
url = "2"
urlencoding = "2"
uuid = { version = "1", features = ["v4", "serde"] }
webbrowser = "1"
